### PR TITLE
fix(semantic_release): updated lock files

### PR DESCRIPTION
**Pull request by JairajJangle**
- fix(semantic_release): updated lock files

### CODE REVIEW

**Comment by qwertychouskie** [comment]
GitHub Issues aren't enabled for this repository, so I'll leave this here: I'm having an issue where this works on Web and iOS, but on Android the element is always returned as not visible.  Any ideas of where to start looking for a root cause?

**Comment by qwertychouskie** [comment]
Hmm, after some debugging, it turns out to be this issue: https://github.com/facebook/react-native/issues/29712

Adding `collapsable={false}` to the View returned at the bottom of `VisibilitySensor.tsx` fixes the issue for me.

**Comment by JairajJangle** [comment]
@qwertychouskie `VisibilitySensor` accepts all props for View, you might be able to directly set `collapsable={false}` for `VisibilitySensor` itself. I will look into this and add a note to the README file.

**Comment by qwertychouskie** [comment]
> @qwertychouskie `VisibilitySensor` accepts all props for `View`, you might be able to directly set `collapsable={false}` for `VisibilitySensor` itself. I will look into this and add a note to the README file.

That's what I'm doing right now, but ideally the library itself would set it as the issue is a weird, non-obvious failure that probably took me a couple hours to track down.

**Comment by mharrison-nzme** [comment]
I just encountered this issue myself, and yes adding `collapsable={false}` to <VisibilitySensor> has resolved the issue.

"react": "18.2.0",
"react-native": "0.72.17",
"@futurejj/react-native-visibility-sensor": "^1.3.8",

**Comment by JairajJangle** [comment]
If you're encountering this issue, please share a **minimal reproducible example**. An **Expo Snack** would be perfect.

This will help me and fellow contributors identify the root cause and work on a more robust fix 🙏

**Comment by michaelpomogajko** [comment]
If you don't want to set collapsable everytime you use it, just use this simple patch 
```
diff --git a/node_modules/@futurejj/react-native-visibility-sensor/src/VisibilitySensor.tsx b/node_modules/@futurejj/react-native-visibility-sensor/src/VisibilitySensor.tsx
index 3afeba2..57b95e9 100644
--- a/node_modules/@futurejj/react-native-visibility-sensor/src/VisibilitySensor.tsx
+++ b/node_modules/@futurejj/react-native-visibility-sensor/src/VisibilitySensor.tsx
@@ -271,7 +271,7 @@ const VisibilitySensor = forwardRef<VisibilitySensorRef, VisibilitySensorProps>(
     ]);
 
     return (
-      <View ref={localRef} {...rest}>
+      <View ref={localRef} {...rest} collapsable={false}>
         {children}
       </View>
     );

```

**Pull request merged**
